### ISSUE TITLE
Controller issues - Nimbus

### ISSUE THREAD

**Issue by pjpalomaki** [Izhido/Quake_For_OSX#2]
Hey, well done for the port, works brilliantly on AppleTV!

I do have some controller issues with SteelSeries Nimbus. The buttons don't seem to match the readme.md - what works out of the box is this: both thumb sticks (move & look), right button (weapon switch), B (menu), A & B in-menu (select / cancel). But I can add the missing bindings in menu so that's not an issue.

The biggest issue is the right stick sensitivity (mouse look - way too high) and even adjusting mouse sensitivity to lowest in menu doesn't bring it down enough. I haven't tried adjusting the speed in console (sensitivity, m_pitch, m_yaw). Is there a way to adjust a multiplier or something in the code?

**Comment by Izhido** [comment]
I did a few changes to the README to reflect better the current bindings of the game controller. Now, buttons in the game controller currently map to keys in the game, and they can only be changed in code (A = ENTER, B / Menu = ESC, D-Pad = Arrow keys, Right trigger = Control key). The only exception being Right shoulder, which currently does an "impulse 10". You can use this information to create your desired bindings.

The sensitivity of the right thumbstick can be changed with the "in_anglescale" cvar. I decided to create a new cvar instead of reusing "sensitivity" since this pertains to the mouse, and remember we have already an MacOS target up & running in this project. 

There is an unfortunate issue with this game in the Apple TV: As of the time of this writing, you cannot use iTunes File Sharing to transfer files to and from the device. So be sure to write your bindings and cvars to config.cfg within the shared id1/ directory before starting the game.

I did additional fixes to the controller code - the player view was resetting its position after moving the right thumbstick, even in the middle of moving it. Also, pressing Menu/Pause was doing duplicate calls to K_ESCAPE, and (unneeded) calls to K_PAUSE.
