### ISSUE TITLE
Unable to save game

### ISSUE THREAD

**Issue by pjpalomaki** [Izhido/Quake_For_OSX#3]
Thanks again for a great port!

I'm sure you're already aware of the issue but I can't save a game on AppleTV. When I select a single player save slot, I get something like this:

Saving to /var/containers/bundle/application/[some UID key or something]/quake_tvos.app/id1/s0.sav...
Error: couldn't open.

**Comment by Izhido** [comment]
Regrettably, I'm being forced to close this issue because of an unexpected problem with the Apple TV 4:

As of the time of this writing, apps are denied access to their own "Documents" directory in tvOS. Meaning, there is no way to write or read back files from a permanent storage associated with the app. As such, .sav files cannot be created to save games. Sorry about that.

**Comment by Izhido** [comment]
Closing the issue.
